### ISSUE TITLE
Error when executing example on Matlab r2017b

### ISSUE THREAD

**Issue by ghost** [FranckLab/LD-3D-TFM#1]
Hi,
this is Francesco Pasqualini from Harvard University - thanks for sharing the code. 

I am trying to get familiar with the algorithm but I get an error when executing the example on Matlab R2017b. Do you know if there is any compatibility issue with the newer versions of Matlab? 

Alternatively, I might be doing something wrong. I had to move the example script and file in the main folder as funIDVC couldn't find the volume even if all the folders were in the path. Can that be the reason for the current error? Any advice?

Thanks

the error log is:
![image](https://user-images.githubusercontent.com/30417472/34618381-98b44850-f20c-11e7-9bda-2b53c0b087d5.png)

**Comment by ghost** [comment]
Up. Any suggestion? Thanks in advance, Francesco.

**Comment by mohakpatel** [comment]
Hi Francesco, 
Thanks for pointing out this issue. We are working on fixing the problem. The updated code should be online in a few days. I let you know about it. 

Best,
Mohak

**Comment by ghost** [comment]
Thanks Mohak - I kept trying things out and couldn't get it to work. Glad to know it is something you are tackling and look forward to the updated version. Thanks again, Francesco

**Comment by mohakpatel** [comment]
Hi Francesco, 
We have fixed the problem and uploaded the code. Let me know if you have any issues running the new code. 

Best,
Mohak

**Comment by ghost** [comment]
I can confirm that it's working on my computer as well. Thanks!
